version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_SUPERUSER_PASSWORD:?POSTGRES_SUPERUSER_PASSWORD is required}
      DEV_DB_PASSWORD: ${DEV_DB_PASSWORD:?DEV_DB_PASSWORD is required}
      STAGING_DB_PASSWORD: ${STAGING_DB_PASSWORD:?STAGING_DB_PASSWORD is required}
      PROD_DB_PASSWORD: ${PROD_DB_PASSWORD:?PROD_DB_PASSWORD is required}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d:ro
    profiles:
      - dev
      - staging
      - prod

volumes:
  postgres-data:
