# Generated by Django 5.2.8 on 2025-11-20 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed amount"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("applies_to_shipping", models.BooleanField(default=False)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("mobile", models.CharField(blank=True, max_length=50, null=True)),
                ("tax_number", models.CharField(max_length=50, unique=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=5)),
                ("compounding", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "additional_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "loyalty_status",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                            ("Platinum", "Platinum"),
                        ],
                        default="None",
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("Email", "Email"),
                            ("SMS", "SMS"),
                            ("Phone", "Phone"),
                            ("None", "None"),
                        ],
                        default="None",
                        max_length=10,
                    ),
                ),
                ("billing_address", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("email__isnull", False)),
                        fields=("first_name", "last_name", "email"),
                        name="uniq_customer_name_email",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("phone_number__isnull", False)),
                        fields=("first_name", "last_name", "phone_number"),
                        name="uniq_customer_name_phone",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("preferred_contact_method", "None"),
                            ("email__isnull", False),
                            ("phone_number__isnull", False),
                            _connector="OR",
                        ),
                        name="preferred_contact_requires_contact",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("invoice_number", models.CharField(max_length=100, unique=True)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Cash", "Cash"),
                            ("Card", "Card"),
                            ("Mobile", "Mobile"),
                            ("GiftCard", "Gift Card"),
                            ("Account", "Account"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("xml", models.TextField(blank=True, null=True)),
                ("qr_base64", models.TextField(blank=True, null=True)),
                (
                    "qr_image",
                    models.ImageField(blank=True, null=True, upload_to="invoices/qr/"),
                ),
                (
                    "e_invoice_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "invoice_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "sequence_income_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "currency_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "total_before_discount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="app.customer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.seller",
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sku", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("taxable", models.BooleanField(default=True)),
                ("stock_on_hand", models.PositiveIntegerField(default=0)),
                ("stock_reserved", models.PositiveIntegerField(default=0)),
                ("reorder_level", models.PositiveIntegerField(default=0)),
                ("reorder_quantity", models.PositiveIntegerField(default=0)),
                ("supplier_id", models.UUIDField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["sku"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("base_price__gte", 0)),
                        name="base_price_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("unit_cost__gte", 0)),
                        name="unit_cost_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("base_price__gte", models.F("unit_cost"))),
                        name="base_price_above_cost",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("stock_reserved__lte", models.F("stock_on_hand"))
                        ),
                        name="reserved_not_exceed_on_hand",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvoiceTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.invoice"
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.tax"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.discount"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.invoice"
                    ),
                ),
            ],
            options={
                "unique_together": {("invoice", "discount")},
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "line_tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "line_discount_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_after_discount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="app.invoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.item"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="line_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("unit_price__gte", 0)),
                        name="line_unit_price_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("line_subtotal__gte", 0)),
                        name="line_subtotal_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("line_tax_total__gte", 0)),
                        name="line_tax_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("discount_amount__gte", 0)),
                        name="line_discount_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("discount_amount__lte", models.F("line_subtotal"))
                        ),
                        name="line_discount_lte_subtotal",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)), name="subtotal_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_total__gte", 0)), name="tax_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_total__gte", 0)),
                name="discount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_due__gte", 0)), name="total_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "sent", "paid", "void"])),
                name="valid_invoice_status",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoicetax",
            unique_together={("invoice", "tax")},
        ),
    ]
