# Generated by Django 5.2.8 on 2025-12-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoice",
            name="valid_invoice_status",
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DRAFT", "Draft"),
                    ("ISSUED", "Issued"),
                    ("PAID", "Paid"),
                    ("DECLINED", "Declined"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["ACTIVE", "DRAFT", "ISSUED", "PAID", "DECLINED"])
                ),
                name="valid_invoice_status",
            ),
        ),
    ]
