# Generated by Django 5.2.8 on 2025-11-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invoicediscount",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="invoicetax",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="discount",
            name="ends_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="starts_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name="invoicediscount",
            constraint=models.UniqueConstraint(
                fields=("invoice", "discount"), name="unique_invoice_discount"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicetax",
            constraint=models.UniqueConstraint(
                fields=("invoice", "tax"), name="unique_invoice_tax"
            ),
        ),
    ]
