# Generated by Django 5.2.8 on 2025-12-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_invoice_valid_invoice_status_invoice_is_draft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total_due",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
