# Generated by Django 5.2.8 on 2025-11-24 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_invoicediscount_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicetax",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="invoicetax",
            name="tax",
        ),
        migrations.RemoveConstraint(
            model_name="invoice",
            name="tax_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="invoicelineitem",
            name="line_tax_non_negative",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="tax_total",
        ),
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="line_tax_total",
        ),
        migrations.RemoveField(
            model_name="item",
            name="taxable",
        ),
        migrations.DeleteModel(
            name="InvoiceTax",
        ),
        migrations.DeleteModel(
            name="Tax",
        ),
    ]
