# Generated by Django 5.2.8 on 2025-11-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_invoicetax_invoice_remove_invoicetax_tax_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveConstraint(
            model_name="customer",
            name="uniq_customer_name_email",
        ),
        migrations.RemoveConstraint(
            model_name="customer",
            name="uniq_customer_name_phone",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_name",
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("name", "email"),
                name="uniq_customer_name_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number__isnull", False)),
                fields=("name", "phone_number"),
                name="uniq_customer_name_phone",
            ),
        ),
    ]
