# Generated by Django 5.2.8 on 2025-12-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_invoice_total_due"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="is_draft",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="currency_name",
            field=models.CharField(blank=True, default="JOD", max_length=50, null=True),
        ),
    ]
