# Generated by Django 5.2.8 on 2025-12-01 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_invoice_is_draft_alter_invoice_currency_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="discount_value",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="total_before_discount",
        ),
    ]
