# Generated by Django 5.2.8 on 2025-11-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["-issue_date"]},
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="invoice_date",
            new_name="issue_date",
        ),
        migrations.AlterField(
            model_name="customer",
            name="additional_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
