# Generated by Django 5.2.8 on 2025-11-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_invoice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicelineitem",
            name="item_name",
            field=models.CharField(default="Unknown Item", max_length=255),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.item",
            ),
        ),
    ]
