# Generated by Django 5.2.8 on 2025-12-03 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_invoice_valid_invoice_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="postal_code",
        ),
    ]
