# Generated by Django 5.2.8 on 2025-11-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_invoicelineitem_item_name_alter_invoicelineitem_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="discount_total",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_due",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="line_discount_total",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="line_subtotal",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="item",
            name="base_price",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="item",
            name="unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
    ]
