# Generated by Django 5.2.8 on 2025-12-03 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_remove_customer_postal_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("silver_threshold", models.PositiveIntegerField(default=50)),
                ("gold_threshold", models.PositiveIntegerField(default=250)),
                ("platinum_threshold", models.PositiveIntegerField(default=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Loyalty settings",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="loyalty_status_locked",
            field=models.BooleanField(
                default=False,
                help_text="Lock the loyalty status to prevent automatic changes based on invoice count.",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
