# Generated by Django 5.2.8 on 2025-11-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_invoice_discount_total_alter_invoice_subtotal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total_due",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
