# Generated by Django 5.2.8 on 2025-12-03 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_loyaltysettings_customer_loyalty_status_locked_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoicelineitem",
            old_name="item_name",
            new_name="description",
        ),
    ]
