# Generated by Django 5.2.8 on 2025-11-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_invoice_total_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total_due",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
