# Generated by Django 5.2.8 on 2025-11-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_invoice_total_due"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoice",
            name="valid_invoice_status",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("paid", "Paid"),
                    ("void", "Void"),
                    ("active", "Active"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "sent", "paid", "void", "active"])
                ),
                name="valid_invoice_status",
            ),
        ),
    ]
