# Generated by Django 5.2.8 on 2025-12-05 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_rename_item_name_invoicelineitem_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoicelineitem",
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
            },
        ),
    ]
