# Generated by Django 5.2.8 on 2025-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_remove_invoice_valid_invoice_status_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoice",
            name="valid_invoice_status",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SENT", "Sent"),
                    ("PAID", "Paid"),
                    ("VOID", "Void"),
                    ("ACTIVE", "Active"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["DRAFT", "SENT", "PAID", "VOID", "ACTIVE"])
                ),
                name="valid_invoice_status",
            ),
        ),
    ]
