# Generated by Django 5.2.8 on 2025-11-24 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_remove_invoice_valid_invoice_status_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoice",
            name="valid_invoice_status",
        ),
    ]
