# Generated by Django 5.2.8 on 2025-11-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_remove_invoice_valid_invoice_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["ACTIVE", "PAID", "VOID", "CANCELLED", "DECLINED"])
                ),
                name="valid_invoice_status",
            ),
        ),
    ]
