# Generated by Django 5.2.8 on 2025-11-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_invoice_valid_invoice_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoice",
            name="valid_invoice_status",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("ISSUED", "Issued"),
                    ("PAID", "Paid"),
                    ("VOID", "Void"),
                    ("CANCELLED", "Cancelled"),
                    ("DECLINED", "Declined"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["ACTIVE", "ISSUED", "PAID", "VOID", "CANCELLED", "DECLINED"],
                    )
                ),
                name="valid_invoice_status",
            ),
        ),
    ]
