name: Django CI

on:
  push:
    branches: ["main", "work"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Django checks
        env:
          DATABASE_URL: sqlite:///./ci.sqlite3
        run: python manage.py check
      - name: Run migrations
        env:
          DATABASE_URL: sqlite:///./ci.sqlite3
        run: python manage.py migrate --noinput
